[package]
name = "lcowsay"
version = "0.3.2"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"
description = "Cowsay, but combined with lolcat."
readme = "README.md"
repository = "https://github.com/davidkna/lcowsay-rs"
documentation = "https://docs.rs/lcowsay/"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lcowsay"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = ["lcat", "clap"]

[dependencies]
hyphenation = "0.8.3"
textwrap = { version = "0.14.1", features = ["hyphenation"] }
unicode-width = "0.1.8"

lcat = { version = "0.7.2", optional = true }
clap = { version = "3.0.0-beta.2", optional = true }

# Allocator
mimalloc = { version = "0.1.26", optional = true, default-features = false }
