[package]
name = "lcowsay"
version = "0.1.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"
description = "Cowsay, but combined with lolcat."
readme = "README.md"
repository = "https://github.com/davidkna/lcowsay-rs"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lcowsay"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = ["lcat", "structopt"]

[dependencies]
hyphenation = { version = "0.7", features = ["embed_all"] }
textwrap = { version = "0.11", features = ["hyphenation"] }
unicode-width = "0.1.5"

lcat = { version = "0.2", optional = true }
structopt = { version = "0.3" , optional = true }

# Allocator
mimalloc = { version = "0.1.19", optional = true, default-features = false }
