[package]
name = "lcowsay"
version = "0.2.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lcowsay"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = ["lcat", "structopt"]

[dependencies]
hyphenation = { version = "0.7", features = ["embed_all"] }
textwrap = { version = "0.11", features = ["hyphenation"] }
unicode-width = "0.1.5"

lcat = { git = "https://github.com/davidkna/lcat-rs", optional = true }
structopt = { version = "0.3" , optional = true }
